[tool.black]
line-length = 88  # Numero massimo di caratteri per riga
target-version = ['py38', 'py39', 'py310', 'py311']  # Versioni Python supportate
skip-string-normalization = false  # Imposta a true se non vuoi che Black cambi gli apici delle stringhe
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.pytest_cache
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"  # Fa in modo che isort segua lo stile di Black
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
